CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY,
    BOOK_NAME VARCHAR(50) NOT NULL,
    AUTHOR_NAME VARCHAR(30) NOT NULL,
    BOOK_COUNT INT CHECK (BOOK_COUNT > 0) NOT NULL
);

INSERT INTO BOOKS VALUES
(1, 'Lost Between Lines', 'Riya Kapoor', 4),
(2, 'Whispers of Silence', 'Aman Joshi', 6),
(3, 'Fragments of Yesterday', 'Kunal Shah', 2),
(4, 'Pages Beyond Reality', 'Mehul Jain', 5),
(5, 'Nightfall Diaries', 'Sneha Patel', 1);

SELECT * FROM BOOKS;



CREATE TABLE LIBRARY_VISITORS (
    USER_ID INT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    AGE INT CHECK (AGE >= 17) NOT NULL,
    EMAIL VARCHAR(40) UNIQUE NOT NULL
);

INSERT INTO LIBRARY_VISITORS VALUES
(601, 'Rohit Verma', 20, 'rohit.verma@gmail.com'),
(602, 'Priya Malhotra', 22, 'priya.m@gmail.com'),
(603, 'Sahil Gupta', 19, 'sahil.gupta@gmail.com');

SELECT * FROM LIBRARY_VISITORS;


CREATE TABLE BOOK_ISSUE (
    BOOK_ISSUE_ID INT PRIMARY KEY,
    USER_ID INT REFERENCES LIBRARY_VISITORS(USER_ID),
    BOOK_ID INT REFERENCES BOOKS(BOOK_ID),
    ISSUE_DATE DATE
);


INSERT INTO BOOK_ISSUE VALUES
(201, 601, 2, '2026-01-11'),
(202, 602, 4, '2026-01-12');

SELECT * FROM BOOK_ISSUE;

CREATE ROLE LIBRARIAN
WITH LOGIN PASSWORD '123654';

SELECT CURRENT_USER;


GRANT SELECT, INSERT, UPDATE, DELETE
ON BOOKS, LIBRARY_VISITORS, BOOK_ISSUE
TO LIBRARIAN;


REVOKE UPDATE, DELETE
ON BOOKS
FROM LIBRARIAN;

SELECT * FROM BOOKS;
SELECT * FROM LIBRARY_VISITORS;
SELECT * FROM BOOK_ISSUE;
